# image and docs: https://hub.docker.com/r/easysoft/zentao

version: '3.8'

services:
  zentao:
    image: easysoft/zentao:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - zentao:/www/zentaopms
    environment:
      # The belows vars is need, otherwise container error
      zentao_DB_HOST: ${DB_MYSQL_HOST}
      zentao_DB_PASSWORD: ${DB_MYSQL_PASSWORD}
    links: 
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: zentao-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  zentao: